baseURL = 'https://blog.larryxue.dev'
languageCode = 'en-us'
title = "Yujian's blog"
theme = 'PaperMod'
enableEmoji = true
enableRobotsTXT = true
hasCJKLanguage = true
showReadingTime = true
showWordCount = true

[params]
author = "Yujian"
ShowRssButtonInSectionTermList = true
ShowReadingTime = true
ShowWordCount = true
ShowFullTextinRSS = true
  [params.homeInfoParams]
    enabled = true
    Title = 'Exploring the World and Me'
    Content = '一个活着的人'
    Image = 'images/hero-img.png'
    AlignSocialIconsTo = 'left'

  [params.busuanzi]
    enable = true

[[params.socialIcons]]
  name = "GitHub"
  url = "https://github.com/larry-xue"
[[params.socialIcons]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/larry-xue-588386212/"
[[params.socialIcons]]
  name = "Email"
  url = "mailto:azoux0311@gmail.com"
[[params.socialIcons]]
  name = "Portfolio"
  url = "https://larryxue.dev"
[[params.socialIcons]]
  name = "RSS"
  url = "https://blog.larryxue.dev/index.xml"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[menus]
  [[menus.main]]
    name = "Search"
    url = "/search"
    weight = 100
    identifier = "search"
    pre = "<i class='fas fa-search'></i>"
  [[menus.main]]
    name = "Posts"
    url = "/posts"
    weight = 80
    identifier = "posts"
    pre = "<i class='fas fa-file-alt'></i>"
  [[menus.main]]
    name = "Tags"
    url = "/tags"
    weight = 85
    identifier = "tags"
    pre = "<i class='fas fa-tags'></i>"
  [[menus.main]]
    name = "Archive"
    url = "/archives"
    weight = 90
    identifier = "archives"
    pre = "<i class='fas fa-archive'></i>"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
